name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags: v*

permissions:
  contents: write

jobs:
  build-project:
    name: Build 🧱
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    permissions:
      actions: write
      contents: read
